name: Build

on:
  workflow_call:
    secrets:
      SIGNATURE_KEY:
        required: true
    outputs:
      combined-fwbundle-artifact:
        description: "The combined firmware bundle artifact name"
        value: ${{ jobs.build-combined-fwbundle.outputs.combined-fwbundle-artifact }}
  push:
    branches:
      - main
      - v*-branch
      - collab*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - v*-branch
      - collab*

concurrency:
  group: ${{ github.workflow }}-build-fw-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  genboards:
    runs-on: ubuntu-24.04
    outputs:
      boards: ${{ steps.genboards.outputs.boards }}
    steps:
      - uses: actions/checkout@v4
      - id: genboards
        run: |
          echo "boards=$(jq -c '.' .github/boards.json)" | tee -a $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-24.04
    needs: genboards
    strategy:
      fail-fast: false
      matrix:
        board: ${{ fromJson(needs.genboards.outputs.boards) }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms
      - uses: hendrikmuhs/ccache-action@v1.2.14
      - uses: ./tt-zephyr-platforms/.github/workflows/prepare-zephyr
        with:
          app-path: tt-zephyr-platforms

      # Only perform this step for tagged releases, since it increases CI duration by 2 minutes
      - name: Fetch Tags
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          west forall -c 'git fetch --unshallow || true'

      - name: Generate BOARD
        working-directory: tt-zephyr-platforms
        shell: bash
        run: |
          BOARD="$(./scripts/rev2board.sh "${{ matrix.board }}")"
          echo "BOARD=$BOARD" | tee "$GITHUB_ENV"

      - shell: bash
        run: |
          SIGNATURE_KEY_FILE="$(mktemp)"
          echo "${{ secrets.SIGNATURE_KEY }}" | base64 -d > "$SIGNATURE_KEY_FILE"
          SZ=$(wc -c "$SIGNATURE_KEY_FILE" | awk '{print $1}')
          if [ $SZ -gt 42 ]; then
            echo "SIGNATURE_KEY_FILE=$SIGNATURE_KEY_FILE" >> "$GITHUB_ENV"
          fi

      - name: Build firmware bundle
        shell: bash
        run: |
          if [ "$BOARD" = "" ]; then
            echo "BOARD is not set"
            exit 1
          fi

          EXTRA_ARGS="--"
          EXTRA_ARGS+=" -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y"
          if [ -n "$SIGNATURE_KEY_FILE" ]; then
            EXTRA_ARGS+=" -DSB_CONFIG_BOOT_SIGNATURE_KEY_FILE=\"$SIGNATURE_KEY_FILE\""
          fi

          west build \
            -d build-${{ matrix.board }} \
            --sysbuild \
            -p \
            -b $BOARD \
            tt-zephyr-platforms/app/smc \
            $EXTRA_ARGS

      - name: Verify firmware signature
        shell: bash
        run: |
          if [ -z "$SIGNATURE_KEY_FILE" ]; then
            echo "SIGNATURE_KEY_FILE is not set, skipping signature verification"
          else
            # verify that built images for smc and dmc fw are signed
            # imgtool returns a non-zero exit code if the image is not signed
            if [ "${{ matrix.board }}" != "galaxy" ]; then
              imgtool verify --key "$SIGNATURE_KEY_FILE" build-${{ matrix.board }}/dmc/zephyr/zephyr.signed.bin
            fi
            imgtool verify --key "$SIGNATURE_KEY_FILE" build-${{ matrix.board }}/recovery/zephyr/zephyr.signed.bin
            imgtool verify --key "$SIGNATURE_KEY_FILE" build-${{ matrix.board }}/smc/zephyr/zephyr.signed.bin
          fi

      - name: Upload firmware assets
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}
          path: |
            build-${{ matrix.board }}/update.fwbundle
            build-${{ matrix.board }}/**/.config
            build-${{ matrix.board }}/**/devicetree_generated.h
            build-${{ matrix.board }}/**/zephyr.bin
            build-${{ matrix.board }}/**/zephyr.dts
            build-${{ matrix.board }}/**/zephyr.elf
            build-${{ matrix.board }}/**/zephyr.hex
            build-${{ matrix.board }}/**/zephyr.map
            build-${{ matrix.board }}/**/zephyr.signed.bin
            build-${{ matrix.board }}/**/zephyr.signed.hex
            build-${{ matrix.board }}/**/zephyr.stat

      - name: Build recovery firmware
        shell: bash
        run: |

          EXTRA_ARGS="--"
          EXTRA_ARGS+=" -DEXTRA_CONF_FILE=sysbuild/recovery.conf"
          EXTRA_ARGS+=" -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y"
          if [ -n "$SIGNATURE_KEY_FILE" ]; then
            EXTRA_ARGS+=" -DCONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=n"
            EXTRA_ARGS+=" -DCONFIG_MCUBOOT_SIGNATURE_KEY_FILE=\"$SIGNATURE_KEY_FILE\""
          fi

          west build \
            -d build-recovery \
            -p \
            -b tt_blackhole@p100a/tt_blackhole/smc \
            tt-zephyr-platforms/app/smc \
            $EXTRA_ARGS

      - name: Verify recovery signature
        shell: bash
        run: |
          if [ -z "$SIGNATURE_KEY_FILE" ]; then
            echo "SIGNATURE_KEY_FILE is not set, skipping signature verification"
          else
            # verify that built images for smc and dmc fw are signed
            # imgtool returns a non-zero exit code if the image is not signed
            imgtool verify --key "$SIGNATURE_KEY_FILE" build-recovery/zephyr/zephyr.signed.bin
          fi

      - name: Upload recovery assets
        uses: actions/upload-artifact@v4
        with:
          name: recovery-${{ matrix.board }}
          path: |
            build-recovery/**/.config
            build-recovery/**/devicetree_generated.h
            build-recovery/**/zephyr.bin
            build-recovery/**/zephyr.dts
            build-recovery/**/zephyr.elf
            build-recovery/**/zephyr.hex
            build-recovery/**/zephyr.map
            build-recovery/**/zephyr.stat
            build-recovery/**/zephyr.signed.bin

      - name: Build assembly firmware
        if: ${{ matrix.board == 'p150a' || matrix.board == 'p300a' }}
        shell: bash
        run: |
          if [ "$BOARD" = "" ]; then
            echo "BOARD is not set"
            exit 1
          fi

          EXTRA_ARGS="--"
          EXTRA_ARGS+=" -DCONFIG_COMPILER_WARNINGS_AS_ERRORS=y"
          EXTRA_ARGS+=" -DCONFIG_TT_ASSEMBLY_TEST=y"
          if [ -n "$SIGNATURE_KEY_FILE" ]; then
            EXTRA_ARGS+=" -DCONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=n"
            EXTRA_ARGS+=" -DSB_CONFIG_BOOT_SIGNATURE_KEY_FILE=\"$SIGNATURE_KEY_FILE\""
          fi

          west build \
            -d build-assembly-test-${{ matrix.board }} \
            --sysbuild \
            -S rtt-console \
            -p \
            -b tt_blackhole@${{ matrix.board }}/tt_blackhole/dmc \
            tt-zephyr-platforms/app/dmc \
            $EXTRA_ARGS

      - name: Verify assembly firmware signature
        if: ${{ matrix.board == 'p150a' || matrix.board == 'p300a' }}
        shell: bash
        run: |
          # verify that built images for smc and dmc fw are signed
          # imgtool returns a non-zero exit code if the image is not signed
          imgtool verify --key "$SIGNATURE_KEY_FILE" build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.signed.bin

      - name: Upload assembly-fw assets
        if: ${{ matrix.board == 'p150a' || matrix.board == 'p300a' }}
        uses: actions/upload-artifact@v4
        with:
          name: assembly-fw-${{ matrix.board }}
          path: |
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/.config
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/**/devicetree_generated.h
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.bin
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.dts
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.elf
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.hex
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.map
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.signed.bin
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.signed.hex
            build-assembly-test-${{ matrix.board }}/dmc/zephyr/zephyr.stat

      - name: Upload mcuboot assets
        if: ${{ matrix.board == 'p150a' || matrix.board == 'p300a' }}
        uses: actions/upload-artifact@v4
        with:
          name: assembly-mcuboot-${{ matrix.board }}
          path: |
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/.config
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/**/devicetree_generated.h
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/zephyr.bin
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/zephyr.dts
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/zephyr.elf
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/zephyr.hex
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/zephyr.map
            build-assembly-test-${{ matrix.board }}/mcuboot/zephyr/zephyr.stat

      - name: Build Recovery Bundle
        shell: bash
        if: ${{ matrix.board != 'galaxy' }}
        run: |
          python3 tt-zephyr-platforms/scripts/tooling/blackhole_recovery/prepare-recovery-bundle.py \
            --board ${{ matrix.board }} \
            --signing-key "$SIGNATURE_KEY_FILE" \
            fw-pack-${{ matrix.board }}-recovery.tar.gz

      - name: Upload Recovery Assets
        if: ${{ matrix.board != 'galaxy' }}
        uses: actions/upload-artifact@v4
        with:
          name: firmware-recovery-${{ matrix.board }}
          path: |
            fw-pack-${{ matrix.board }}-recovery.tar.gz

      - name: Build preflash firmware
        if: ${{ matrix.board == 'p100a' }}
        shell: bash
        run: |
          # reuse the output of the previous "Build firmware bundle" step
          TTZP="$PWD/tt-zephyr-platforms"
          YAML_PATH="$TTZP/boards/tenstorrent/tt_blackhole/bootfs/preflash-bootfs.yaml"
          "$TTZP/scripts/tt_boot_fs.py" \
            mkfs \
            "$YAML_PATH" \
            preflash.ihex \
            --build-dir "build-${{ matrix.board }}" \
            --hex

      - name: Upload preflash
        uses: actions/upload-artifact@v4
        if: ${{ matrix.board == 'p100a' }}
        with:
          name: preflash-fw
          path: |
            preflash.ihex

  build-combined-fwbundle:
    runs-on: ubuntu-24.04
    needs: build
    outputs:
      combined-fwbundle-artifact: ${{ steps.set_combined_fwbundle_output.outputs.combined_fwbundle_artifact }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms

      - name: Download firmware artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: firmware-*
          path: tt-zephyr-platforms

      - name: Build Combined Firmware Bundle
        shell: bash
        run: |
          pip install pykwalify intelhex imgtool
          BUNDLE_TEMP_PREFIX="$PWD/tt-zephyr-platforms/firmware-" \
            ./tt-zephyr-platforms/scripts/build-combined-fwbundle.sh

      - name: Upload Combined Firmware Bundle Assets
        uses: actions/upload-artifact@v4
        with:
          name: combined-fwbundle
          path: |
            fw_pack*.fwbundle

      - id: set_combined_fwbundle_output
        run: echo "combined_fwbundle_artifact=combined-fwbundle" >> $GITHUB_OUTPUT

  build-bh-flm:
    runs-on: ubuntu-24.04
    name: Build Blackhole Flash Loader Module
    steps:
      - uses: actions/checkout@v4
        with:
          path: tt-zephyr-platforms
      - uses: hendrikmuhs/ccache-action@v1.2.14
      - uses: ./tt-zephyr-platforms/.github/workflows/prepare-zephyr
        with:
          app-path: tt-zephyr-platforms
      - name: Build Flash Loader Module
        working-directory: ./tt-zephyr-platforms/scripts/tooling/blackhole_recovery/data/bh_flm
        shell: bash
        run: |
          ./build-flm.sh

  build-combined-recovery:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download recovery artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: firmware-recovery-*

      - name: Build Combined Recovery Bundle
        shell: bash
        run: |
          BOARDS="$(jq -r -c ".[]" .github/boards.json)"
          BOARDS="${BOARDS//$'\n'/ }" # Remove embedded newlines

          find . -name '*.tar.gz' -ls

          # Combine recovery bundles
          mkdir firmware-recovery
          for REV in ${BOARD_REVS[@]}; do
            if [[ "$REV" == "galaxy" ]]; then
              continue
            fi
            tar xf firmware-recovery-$REV/fw-pack-$REV-recovery.tar.gz -C firmware-recovery
          done
          tar zcf fw-pack-recovery.tar.gz -C firmware-recovery .

      - name: Upload Combined Recovery Bundle Assets
        uses: actions/upload-artifact@v4
        with:
          name: combined-recovery
          path: |
            fw-pack-recovery.tar.gz
